### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Fookiwara** [zelenin/go-mediainfo#1]
I have the following error when building my application:
# github.com/zelenin/go-mediainfo
In file included from ../github.com/zelenin/go-mediainfo/mediainfo.go:3:
./mediainfo.h:5:10: fatal error: MediaInfoDLL/MediaInfoDLL.h: No such file or directory
 #include <MediaInfoDLL/MediaInfoDLL.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by zelenin** [comment]
provide more details please

**Comment by Fookiwara** [comment]
I try and use your package under docker from an Alpine3.9 image. But it seems the mediainfo package does not install folder source/mediainfodll...
I use the following instruction to install mediainfo lib:

ARG MEDIAINF_VER="19.04"
RUN \
    # Install packages needed by the build.
    apk add --virtual build-dependencies \
        build-base \
        curl \
        qt5-qtbase-dev \
        libmediainfo-dev \
        && \
    curl -o \
    /tmp/libmediainfo.tar.gz -L \
            "http://mediaarea.net/download/binary/libmediainfo0/${MEDIAINF_VER}/MediaInfo_DLL_${MEDIAINF_VER}_GNU_FromSource.tar.gz" && \
    mkdir -p \
            /tmp/libmediainfo && \
    tar xf /tmp/libmediainfo.tar.gz -C \
            /tmp/libmediainfo --strip-components=1 && \
    cd /tmp/libmediainfo && \
            ./SO_Compile.sh && \
    cd /tmp/libmediainfo/ZenLib/Project/GNU/Library && \
            make install && \
    cd /tmp/libmediainfo/MediaInfoLib/Project/GNU/Library && \
            make install && \
    # cleanup
 apk del --purge \
        build-dependencies && \
 rm -rf \
        /tmp/*

**Comment by zelenin** [comment]
```
FROM golang:1.12.5-alpine3.9

RUN apk add --no-cache \
    build-base \
    libmediainfo-dev

ADD . /src

WORKDIR /src
```

```
package main

import (
	"fmt"
	"github.com/zelenin/go-mediainfo"
	"log"
)

func main() {
	filePath := "./test.mp3"
	file, err := mediainfo.Open(filePath)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	fmt.Println(file.Parameter(mediainfo.StreamAudio, 0, "BitRate"))
	fmt.Println(file.Parameter(mediainfo.StreamAudio, 0, "StreamCount"))
}
```

it works for me.

**Comment by Fookiwara** [comment]
Thanks.
So is it a problem of cleanup in my code?

**Comment by zelenin** [comment]
yes, go app need build-base and libmediainfo-dev for run and build static application. Builded app don't need it.

**Comment by Fookiwara** [comment]
Which mediainfo version your code use? I need the last one (19.04)...

**Comment by zelenin** [comment]
we talk about alpine or ubuntu already? Just use last version from repo.

**Comment by Fookiwara** [comment]
alpine...

**Comment by Fookiwara** [comment]
I just test your code and... everything works! thanks

**Comment by zelenin** [comment]
oh, mediainfo version. I thought you meant the version of ubuntu :-)
Btw, I use last version from repo.

**Comment by zelenin** [comment]
oh, I thought you meant version of Ubuntu :-)
Btw, I use last version from repo

**Comment by zelenin** [comment]
oh, I thought you meant version of Ubuntu :-)
Btw, I use last version from repo
